### ISSUE TITLE
Supporting files?

### ISSUE THREAD

**Issue by tedonmain** [PacktPublishing/Complete-Practical-LINQ-Tutorial-in-C-#1]
These are very interesting and helpful exercises that have been thoughtfully prepared, but it would be nice to have some supporting files to use for the exercises. I have had to create supporting data files as necessary as I proceed through the examples. For example, this is the format for the Parsing a CSV-file section in Chapter 1. Personally, I've not seen a .csv file formatted like this before, but by putting the data in this format the example works as demonstrated in the video.
1;Carlsen,Magnus;2872;NOR;1990
2;Caruana,Fabiano;2822;USA;1992
3;Ding,Liren;2805;CHN;1992
4;Grischuk,Alexander;2777;RUS;1983
5;Nepomniachtchi,Ian;2774;RUS;1990
6;Aronian,Levon;2773;ARM;1982
7;Vachier-Lagrave,Maxime;2770;FRA;1990
8;Mamedyarov,Shakhriyar;2770;AZE;1985
9;Giri,Anish;2768;NED;1994
10;So,Wesley;2765;USA;1993
11;Radjabov,Teimour;2765;AZE;1987
12;Wang,Hao;2758;CHN;1989
13;Anand,Viswanathan;2758;IND;1969
14;Rapport,Richard;2758;HUN;1996
15;Dominguez-Perez,Leinier;2758;USA;1983
16;Duda,Jan-Krzysztof;2758;POL;1966
...

**Comment by sanjeetkumar13** [comment]
Thank you for reflecting on this issue.

We have added the supporting files. Let us know in case of anything else.
